@server=http://localhost:8083
@token=your-secret

### check health
GET {{server}}/api/health HTTP/1.1


### Create a new regisetred user
POST {{server}}/api/register HTTP/1.1
content-type: application/json

{
    "username": "John Doe",
    "email": "test_2@email.com"
}


### get image
GET {{server}}/api/qr/7559609691fe7859683d0ff697534365864facddd11c32d95730162889d19762 HTTP/1.1

### validate opt
POST {{server}}/api/verify HTTP/1.1
content-type: application/json

{
    "otp": "225170",
    "email": "test_2@email.com"
}


### admin endpoint
DELETE  {{server}}/admin/flush-one-time-use HTTP/1.1
content-type: application/json
Authorization: {{token}}

### admin endpoint
DELETE  {{server}}/admin/delete-otu HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "username": "John Doe",
    "email": "test_2@email.com"
}
